### ISSUE TITLE
JWT 유효 시간 및 Refresh Token 사용

### ISSUE THREAD

**Issue by somsom13** [Itaseki/itaseki-backend#81]
우선 JWT 유효시간은 30분으로 설정해놨는데 조금 더 길게할까?
원래 탈취 위험성때문에 Access Token 값은 적게하고 Refresh Token은 길게하더라고,,,
근데 Refresh Token을 하려면 Redis 저장소를 이용해야되서 조금 많이 귀찮게되서,, (사실 하기 싫음 ㅎ,,)
물론 Redis 안쓰고 그냥 DB 상에 저장해도 상관없을거같은데 우테코 스승님의 의견을 듣고 싶슴돠,,,

_Originally posted by @kitaee in https://github.com/Itaseki/itaseki-backend/issues/80#issuecomment-1368709126_

**Comment by somsom13** [comment]
Refresh Token 만들기 귀찮은 마음,,, 백번 이해합니다.

사실 번거로우면 그냥 JWT 유효시간을 길게 하는 것도 괜찮다고 생각하는데 그러면 로그아웃을 어떻게 해야 되지....?! 라는 생각이 초큼 듭니다...

JWT는 한 번 만들어지면 수정을 할 수 없는데, 예를 들어 유효 기간 하루라고 한다면 그 시간 내에 사용자가 로그아웃을 하고 다시 토큰으로 요청을 보냈을 때, 이 사람이 로그아웃된 사용자 이므로 재로그인이 필요하다는 걸 어떻게 식별할 수 있을지

물론 코멘트에 남겨준 것 처럼 그냥 DB를 사용하는 것도 아주 괜찮다고 생각합니다 👍

**Comment by kitaee** [comment]
정말 제 개인적인 생각은 BlackList 객체를 만들어서 사용자가 로그아웃 요청을 하면 이 JWT를 BlackList 객체에 넣어요.
그리고 Spring Security Filter 과정에서 BlackList에서 해당 토큰이 있으면 '아 이 토큰은 로그아웃된 토큰이다. 이 토큰에게는 API를 열어주면 안되겠다.'라고 filter 하는 방법을 생각해봤어요! (사실 다른 프로젝트에서 이미 사용한 방법,,,) 물론 이 방법은 사용자들이 로그아웃을 많이 하면 BlackList 객체에 많이 쌓이면서 토큰을 찾을 때, O(n)만큼 오래 걸리겠지만 사용자가 로그아웃을 많이 안할거같아서  ㅠ

redis를 세팅하면서 완벽하게 구현하는 것도 좋은 공부일 것 같은데 우선 15일까지 리팩토링을 하겠다고 선언해버려서,,, 15일까지 1차 리팩토링을 거치고 그 이후에 2차 리팩토링에 이걸 하는것도 좋을 것 같아요@@!!

**Comment by somsom13** [comment]
오옹 좋은 것 같아요! 
토큰이 BlackList에 포함되어 있는지를 확인할 때의 시간 복잡도가 문제라면 HashSet 을 사용하는 건 어떨까 싶습니다 ㅎㅎ

[자바 Collection 시간 복잡도](https://www.grepiu.com/post/9)

2차 리팩토링 때 해결하는 것도 좋아요~!
